name: Build and deploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy APP
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_NAME}}
          key: ${{secrets.HOST_KEY}}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd /var/www/html
            cd laravel-cloud
            git pull
            echo "Deploy success"
            
         
